/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Inicio;

import Controlador.Login.OperacionesBD;
import Modelo.Beans.Usuarios.Usuarios;
import java.sql.SQLException;
import javax.swing.JOptionPane;


public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        this.setVisible(true);
        this.setSize(600,600);
        this.setLocationRelativeTo(null);
        Login.setVisible(true);
        InicioAdminSYS.setVisible(true);
        InicioGerente.setVisible(true);
        InicioVendedor.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Login = new javax.swing.JPanel();
        loginNombre = new javax.swing.JTextField();
        loginPassword = new javax.swing.JTextField();
        jlabelnombre = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        loginIngresar = new javax.swing.JButton();
        InicioGerente = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ButtonAddVendedor = new javax.swing.JButton();
        ButtonVerVendedores = new javax.swing.JButton();
        ButtonVerInventario = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TFAddVendedorNombre = new javax.swing.JTextField();
        TFAddVendedorPassword = new javax.swing.JTextField();
        AddVendedorDocumento = new javax.swing.JTextField();
        InicioVendedor = new javax.swing.JPanel();
        InicioAdminSYS = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jlabelnombre.setText("Nombre");

        jLabel2.setText("Contraseña");

        loginIngresar.setText("Ingresar");
        loginIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginIngresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LoginLayout = new javax.swing.GroupLayout(Login);
        Login.setLayout(LoginLayout);
        LoginLayout.setHorizontalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlabelnombre)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(loginNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(loginPassword))
                .addGap(111, 111, 111))
            .addGroup(LoginLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(loginIngresar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LoginLayout.setVerticalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabelnombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(loginIngresar)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        getContentPane().add(Login);
        Login.setBounds(0, 0, 400, 300);

        jLabel1.setText("estas en el panel de gerente");

        ButtonAddVendedor.setText("Agregar Vendedor");

        ButtonVerVendedores.setText("Ver Vendedores");

        ButtonVerInventario.setText("Ver Inventario");

        jPanel1.setBackground(new java.awt.Color(84, 106, 102));

        jLabel3.setText("Nombre");

        jLabel4.setText("Documento");

        jLabel5.setText("Contraseña");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addGap(78, 78, 78)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddVendedorDocumento, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(TFAddVendedorPassword)
                    .addComponent(TFAddVendedorNombre))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFAddVendedorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AddVendedorDocumento)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TFAddVendedorPassword)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout InicioGerenteLayout = new javax.swing.GroupLayout(InicioGerente);
        InicioGerente.setLayout(InicioGerenteLayout);
        InicioGerenteLayout.setHorizontalGroup(
            InicioGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InicioGerenteLayout.createSequentialGroup()
                .addGroup(InicioGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(InicioGerenteLayout.createSequentialGroup()
                        .addGroup(InicioGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(InicioGerenteLayout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(jLabel1))
                            .addGroup(InicioGerenteLayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(ButtonAddVendedor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ButtonVerVendedores)))
                        .addGap(12, 12, 12)
                        .addComponent(ButtonVerInventario)))
                .addContainerGap(373, Short.MAX_VALUE))
        );
        InicioGerenteLayout.setVerticalGroup(
            InicioGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InicioGerenteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(InicioGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonAddVendedor)
                    .addComponent(ButtonVerVendedores)
                    .addComponent(ButtonVerInventario))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(422, Short.MAX_VALUE))
        );

        getContentPane().add(InicioGerente);
        InicioGerente.setBounds(0, 0, 754, 712);

        javax.swing.GroupLayout InicioVendedorLayout = new javax.swing.GroupLayout(InicioVendedor);
        InicioVendedor.setLayout(InicioVendedorLayout);
        InicioVendedorLayout.setHorizontalGroup(
            InicioVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        InicioVendedorLayout.setVerticalGroup(
            InicioVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        getContentPane().add(InicioVendedor);
        InicioVendedor.setBounds(0, 0, 400, 300);

        javax.swing.GroupLayout InicioAdminSYSLayout = new javax.swing.GroupLayout(InicioAdminSYS);
        InicioAdminSYS.setLayout(InicioAdminSYSLayout);
        InicioAdminSYSLayout.setHorizontalGroup(
            InicioAdminSYSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        InicioAdminSYSLayout.setVerticalGroup(
            InicioAdminSYSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        getContentPane().add(InicioAdminSYS);
        InicioAdminSYS.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginIngresarActionPerformed
        String userinn = loginNombre.getText();
        String passinn = loginPassword.getText();
        OperacionesBD ope = new OperacionesBD();
        Usuarios usuarioLogueado = (Usuarios)ope.Login(userinn, passinn);
        if (usuarioLogueado == null){
            JOptionPane.showMessageDialog(null, "usuario y/o contraseña erroneos");
            
        }else{
            if(usuarioLogueado.getRol().equalsIgnoreCase("gerente")){
                InicioGerente.setVisible(true);
                InicioAdminSYS.setVisible(false);
                InicioVendedor.setVisible(false);
                Login.setVisible(false);
            }else if (usuarioLogueado.getRol().equalsIgnoreCase("Vendedor")){
                InicioGerente.setVisible(false);
                InicioAdminSYS.setVisible(false);
                InicioVendedor.setVisible(true);
                Login.setVisible(false);
                
            }else if (usuarioLogueado.getRol().equalsIgnoreCase("Administrador")){
                InicioGerente.setVisible(false);
                InicioAdminSYS.setVisible(true);
                InicioVendedor.setVisible(false);
                Login.setVisible(false);
                
            }
        }
    }//GEN-LAST:event_loginIngresarActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddVendedorDocumento;
    private javax.swing.JButton ButtonAddVendedor;
    private javax.swing.JButton ButtonVerInventario;
    private javax.swing.JButton ButtonVerVendedores;
    private javax.swing.JPanel InicioAdminSYS;
    private javax.swing.JPanel InicioGerente;
    private javax.swing.JPanel InicioVendedor;
    private javax.swing.JPanel Login;
    private javax.swing.JTextField TFAddVendedorNombre;
    private javax.swing.JTextField TFAddVendedorPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlabelnombre;
    private javax.swing.JButton loginIngresar;
    private javax.swing.JTextField loginNombre;
    private javax.swing.JTextField loginPassword;
    // End of variables declaration//GEN-END:variables
}
